### ISSUE TITLE
No implementation for Property type 'StrProperty' error.

### ISSUE THREAD

**Issue by iam4k33m** [ch1pset/UESaveTool#10]
The error given is:
`TypeNotImplementedError: No implementation for Property type: 'StrProperty'
    at Factory.createArray (file:///E:/Downloads/UESaveTool-master/UESaveTool-master/models/factories/PropertyFactory.js:20:19)
    at ArrayProperty.deserialize (file:///E:/Downloads/UESaveTool-master/UESaveTool-master/models/properties/ArrayProperty.js:43:41)
    at Tuple.deserialize (file:///E:/Downloads/UESaveTool-master/UESaveTool-master/models/properties/Tuple.js:29:18)
    at Gvas.deserialize (file:///E:/Downloads/UESaveTool-master/UESaveTool-master/models/Gvas.js:25:25)
    at file:///E:/Downloads/UESaveTool-master/UESaveTool-master/uesavetool.js:14:22
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

Node.js v18.17.1`
Note that the StrProperty file exists and is referenced in the index.js

**Comment by ch1pset** [comment]
I'll have to test this on a fresh environment. Would you mind posting your .sav you are trying to view?

I don't have time at the moment to work on this. I haven't actively developed this package in a long time. I can't make any promises that we'll resolve your issue. I'll take a look this weekend.
